### ISSUE TITLE
Echo - subcontroller in a subfolder

### ISSUE THREAD

**Issue by Robbie-Perry** [comp-4711-lab03-rp-kk-jw/starter-route66#5]
This will be a controller found by convention
Make the target link /echo/must/wehave
We want this handled by a conventional controller, i.e. controllers/echo/Must::wehave()
The body of that method should invoke the inherited show method, with the key "5"

**Comment by JeremyWildsmith** [comment]
This controller doesn't work correctly on a LAMP server due to the case sensitivity.
